In [154]:
#Imports
import gym
import tensorflow as tf
import numpy as np
import random
from collections import deque 
env = gym.make('CartPole-v1')

In [155]:
#Global varaible
epsilon = 1

In [167]:
#Constants
REPLAY_MEMORY_SIZE = 10000
MIN_REPLAY_MEMORY_SIZE = 250
MIN_EPSILON = 0.01
EPSILON_DECAY = 0.98
BATCH_SIZE = 32
DISCOUNT = 0.9995
UPDATE_PREDICITON_EVERY = 2

In [157]:
#Model takes in actions and outputs Q values for each action which represnt the predicted score for the action
def create_model():
    model = tf.keras.Sequential([tf.keras.layers.Dense(64,input_shape = (4,)),
                                 tf.keras.layers.Dense(32, activation = 'relu'),
                                 tf.keras.layers.Dense(2, activation = 'linear')])
    model.compile(tf.keras.optimizers.Adam(0.001), loss = 'mse', metrics='accuracy')
    return model

In [158]:
#Create new models
updated_model = create_model()

#Prediction model is created to keep some consitancy in future Q values predictions
#This only gets updated after every couple runthroughs of the enviorment
prediction_model = create_model()
prediction_model.set_weights(updated_model.get_weights())

In [203]:
#Returns a action for the Cart Pole enviorment
#If epsilon is bigger there is a larger chance of performing random actions (exploring)
#Epsilon decays over training iterations and actions become more greedy (exploitation)
def get_action(obs):
    if random.uniform(0, 1) <= epsilon:
        return random.randint(0,1)
    else:
        q_vals = updated_model.predict(obs)
        print(q_vals)
        return np.argmax(q_vals)

In [201]:
#Using expirence and past rewards this trains the model to output higher Q values for actions that have better rewards given the state(input)
def train_model():
    #Test to see if it has enough expirence
    if len(replay_memory) >= MIN_REPLAY_MEMORY_SIZE:
        #Get a ranodm batch of samples from memory
        batch = random.sample(replay_memory, BATCH_SIZE)
        
        #X[0] is the intial observations. Getting the Q outputs for the intial enviorment condtions batch
        X = np.array([x[0] for x in batch]).reshape(BATCH_SIZE,4)
        current_qs_list = updated_model.predict(X)
        
        #X[3] is the new observations. Getting the Q outputs for the new enviorment condtions batch
        future_qs_list = prediction_model.predict(np.array([x[3] for x in batch]).reshape(BATCH_SIZE,4))
        
        y = []
        #Loop calculates what the Q output for each sample should look like    
        for i, (obs, action, reward, new_obs, done) in enumerate(batch):
            #This logic allows Q values to predict future Q values
            if not done:                        
                max_future_q = np.max(future_qs_list[i]) 
                new_q = reward + DISCOUNT * max_future_q #Q value for action should be determined from what the best future Q value is when taking the action
            else:
                new_q = reward #If the action caused the enviorment to terminate then the Q value should be the reward it got

            #changing the expected Q value for the action taken in the sample
            current_qs = current_qs_list[i]
            current_qs[action] = new_q

            y.append(current_qs)
        #Fitting the model to the batch of samples
        #input: State
        #output: Q values with an updated Q value for the action taken in the sample
        updated_model.fit(X, np.array(y), batch_size=BATCH_SIZE, shuffle=False)  

In [205]:
#Trainer

#Stores expirence with enviorment
replay_memory = deque(maxlen = REPLAY_MEMORY_SIZE)

#Initialization
obs, info = env.reset(return_info=True)
prediction_update_couter = 0
atempt = 0

#Allows training to run many times
while atempt < 1000: #can set any number of enviorment runthroughs
    #Retrive the action that should be performed and perfoms it
    action = get_action(np.array(obs).reshape(-1, 4))
    new_obs, reward, done, info = env.step(action)
    
    #Whenever an action is perfromed information of the affect of that action is stored
    replay_memory.append([obs, action, reward, new_obs, done]);
    
    train_model()
    
    #Reset enviorment, decay epsilon, and updated counters when done
    if done:
        obs, info = env.reset(return_info=True)
        
        #epsilon decay
        if epsilon > MIN_EPSILON:
            epsilon *= EPSILON_DECAY
            epsilon = max(MIN_EPSILON, epsilon)
            
        prediction_update_couter += 1
        atempt += 1
    #If not done update the currant state
    else:
        obs = new_obs
    #If we have runthough the enviorment enough times save the model weights and update the prediction model    
    if(prediction_update_couter >= UPDATE_PREDICITON_EVERY):
        updated_model.save_weights('model_weights')
        prediction_model.set_weights(updated_model.get_weights())
        prediction_update_couter = 0


1/1 [==============================] - 0s 14ms/step
[[32.834576 31.321314]]
1/1 [==============================] - 0s 13ms/step
[[32.630146 32.06336 ]]
1/1 [==============================] - 0s 14ms/step
[[32.541485 32.99511 ]]
1/1 [==============================] - 0s 15ms/step
[[32.745472 32.518078]]
1/1 [==============================] - 0s 15ms/step
[[32.615128 33.44111 ]]
1/1 [==============================] - 0s 15ms/step
[[32.772274 32.95506 ]]
1/1 [==============================] - 0s 13ms/step
[[32.781914 32.27622 ]]
1/1 [==============================] - 0s 16ms/step
[[32.478485 33.00816 ]]
1/1 [==============================] - 0s 15ms/step
[[32.4665   32.334923]]
1/1 [==============================] - 0s 15ms/step
[[32.121956 33.077076]]
1/1 [==============================] - 0s 15ms/step
[[32.06719 32.41165]]
1/1 [==============================] - 0s 14ms/step
[[31.87528  31.559795]]
1/1 [==============================] - 0s 15ms/step
[[31.381647 32.130344]]
1/1 [=========

1/1 [==============================] - 0s 23ms/step
[[18.040085 17.99084 ]]
1/1 [==============================] - 0s 13ms/step
[[18.115932 18.566462]]
1/1 [==============================] - 0s 14ms/step
[[18.169447 18.152378]]
1/1 [==============================] - 0s 13ms/step
[[18.120771 18.58724 ]]
1/1 [==============================] - 0s 13ms/step
[[18.268686 18.299032]]
1/1 [==============================] - 0s 13ms/step
[[18.117445 17.632483]]
1/1 [==============================] - 0s 14ms/step
[[18.08855  18.076984]]
1/1 [==============================] - 0s 15ms/step
[[18.041601 18.51292 ]]
1/1 [==============================] - 0s 14ms/step
[[18.189085 18.223083]]
1/1 [==============================] - 0s 15ms/step
[[18.038626 17.556273]]
1/1 [==============================] - 0s 14ms/step
[[18.010618 18.000519]]
1/1 [==============================] - 0s 14ms/step
[[17.980515 18.45553 ]]
1/1 [==============================] - 0s 15ms/step
[[18.113228 18.14613 ]]
1/1 [=======

1/1 [==============================] - 0s 15ms/step
[[19.103287 18.870033]]
1/1 [==============================] - 0s 15ms/step
[[19.145683 19.440891]]
1/1 [==============================] - 0s 14ms/step
[[19.070969 18.904736]]
1/1 [==============================] - 0s 12ms/step
[[19.1104  19.47796]]
1/1 [==============================] - 0s 14ms/step
[[19.031937 18.944   ]]
1/1 [==============================] - 0s 14ms/step
[[19.067183 19.519386]]
1/1 [==============================] - 0s 13ms/step
[[18.899042 19.425543]]
1/1 [==============================] - 0s 15ms/step
[[18.923311 19.03465 ]]
1/1 [==============================] - 0s 14ms/step
[[18.696552 18.32413 ]]
1/1 [==============================] - 0s 15ms/step
[[18.597303 18.72921 ]]
1/1 [==============================] - 0s 14ms/step
[[18.391663 18.032179]]
1/1 [==============================] - 0s 13ms/step
[[18.31149  18.449255]]
1/1 [==============================] - 0s 14ms/step
[[18.12483  17.763523]]
1/1 [=========

1/1 [==============================] - 0s 16ms/step
[[17.740982 17.191353]]
1/1 [==============================] - 0s 15ms/step
[[17.67919  17.608023]]
1/1 [==============================] - 0s 14ms/step
[[17.755322 18.208565]]
1/1 [==============================] - 0s 14ms/step
[[17.78416  17.713692]]
1/1 [==============================] - 0s 12ms/step
[[17.849178 18.306427]]
1/1 [==============================] - 0s 14ms/step
[[17.883135 17.80662 ]]
1/1 [==============================] - 0s 13ms/step
[[17.94135  18.391724]]
1/1 [==============================] - 0s 14ms/step
[[17.981728 17.89367 ]]
1/1 [==============================] - 0s 13ms/step
[[18.03652 18.47555]]
1/1 [==============================] - 0s 14ms/step
[[18.086544 17.98008 ]]
1/1 [==============================] - 0s 14ms/step
[[18.131111 18.56067 ]]
1/1 [==============================] - 0s 15ms/step
[[18.18138  18.070591]]
1/1 [==============================] - 0s 14ms/step
[[18.219498 18.649406]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.4934  18.51937]]
1/1 [==============================] - 0s 14ms/step
[[18.441614 17.860561]]
1/1 [==============================] - 0s 13ms/step
[[18.279547 18.248468]]
1/1 [==============================] - 0s 14ms/step
[[18.260712 18.826996]]
1/1 [==============================] - 0s 14ms/step
[[18.35837  18.359108]]
1/1 [==============================] - 0s 14ms/step
[[18.321266 17.702784]]
1/1 [==============================] - 0s 13ms/step
[[18.160578 18.094532]]
1/1 [==============================] - 0s 15ms/step
[[18.142227 18.6747  ]]
1/1 [==============================] - 0s 14ms/step
[[18.244766 18.202902]]
1/1 [==============================] - 0s 14ms/step
[[18.211313 18.77497 ]]
1/1 [==============================] - 0s 14ms/step
[[18.307024 18.297945]]
1/1 [==============================] - 0s 13ms/step
[[18.261675 18.86767 ]]
1/1 [==============================] - 0s 14ms/step
[[18.350897 18.388468]]
1/1 [=========

1/1 [==============================] - 0s 16ms/step
[[17.797766 17.620731]]
1/1 [==============================] - 0s 14ms/step
[[17.80827  18.224483]]
1/1 [==============================] - 0s 14ms/step
[[17.970442 17.753498]]
1/1 [==============================] - 0s 13ms/step
[[17.97919  18.354061]]
1/1 [==============================] - 0s 14ms/step
[[18.1461   17.880732]]
1/1 [==============================] - 0s 14ms/step
[[18.154263 18.477005]]
1/1 [==============================] - 0s 15ms/step
[[18.321224 17.997423]]
1/1 [==============================] - 0s 14ms/step
[[18.316921 18.585241]]
1/1 [==============================] - 0s 14ms/step
[[18.488476 18.104359]]
1/1 [==============================] - 0s 13ms/step
[[18.478083 18.68834 ]]
1/1 [==============================] - 0s 15ms/step
[[18.647001 18.204689]]
1/1 [==============================] - 0s 13ms/step
[[18.635006 18.78859 ]]
1/1 [==============================] - 0s 14ms/step
[[18.805561 18.303062]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[19.795527 19.976852]]
1/1 [==============================] - 0s 19ms/step
[[19.900412 19.458878]]
1/1 [==============================] - 0s 16ms/step
[[19.7935   20.012983]]
1/1 [==============================] - 0s 14ms/step
[[19.899073 19.498466]]
1/1 [==============================] - 0s 61ms/step
[[19.781256 20.051771]]
1/1 [==============================] - 0s 24ms/step
[[19.88724  19.537903]]
1/1 [==============================] - 0s 16ms/step
[[19.759796 20.089348]]
1/1 [==============================] - 0s 16ms/step
[[19.856804 19.57739 ]]
1/1 [==============================] - 0s 20ms/step
[[19.723368 20.130651]]
1/1 [==============================] - 0s 14ms/step
[[19.829615 19.624727]]
1/1 [==============================] - 0s 13ms/step
[[19.698156 20.181635]]
1/1 [==============================] - 0s 16ms/step
[[19.811117 19.683414]]
1/1 [==============================] - 0s 14ms/step
[[19.676497 20.241991]]
1/1 [=======

1/1 [==============================] - 0s 13ms/step
[[18.90033 18.85813]]
1/1 [==============================] - 0s 13ms/step
[[18.778101 19.431463]]
1/1 [==============================] - 0s 14ms/step
[[18.950634 18.971766]]
1/1 [==============================] - 0s 13ms/step
[[18.991896 18.328835]]
1/1 [==============================] - 0s 14ms/step
[[18.722675 18.715607]]
1/1 [==============================] - 0s 16ms/step
[[18.595268 19.290916]]
1/1 [==============================] - 0s 13ms/step
[[18.794943 18.845304]]
1/1 [==============================] - 0s 14ms/step
[[18.86608  18.213163]]
1/1 [==============================] - 0s 13ms/step
[[18.618372 18.603987]]
1/1 [==============================] - 0s 13ms/step
[[18.506857 19.181864]]
1/1 [==============================] - 0s 14ms/step
[[18.730764 18.743872]]
1/1 [==============================] - 0s 14ms/step
[[18.828371 18.12143 ]]
1/1 [==============================] - 0s 14ms/step
[[18.587889 18.514503]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.342102 19.021603]]
1/1 [==============================] - 0s 14ms/step
[[18.57923  18.595114]]
1/1 [==============================] - 0s 14ms/step
[[18.679903 17.979614]]
1/1 [==============================] - 0s 14ms/step
[[18.408318 18.362803]]
1/1 [==============================] - 0s 15ms/step
[[18.276152 18.93516 ]]
1/1 [==============================] - 0s 14ms/step
[[18.524302 18.509018]]
1/1 [==============================] - 0s 14ms/step
[[18.380415 19.076822]]
1/1 [==============================] - 0s 23ms/step
[[18.619469 18.646591]]
1/1 [==============================] - 0s 15ms/step
[[18.729916 18.030619]]
1/1 [==============================] - 0s 17ms/step
[[18.462416 18.415182]]
1/1 [==============================] - 0s 16ms/step
[[18.333214 18.988184]]
1/1 [==============================] - 0s 15ms/step
[[18.588388 18.55998 ]]
1/1 [==============================] - 0s 16ms/step
[[18.44546 19.12773]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.644115 18.615726]]
1/1 [==============================] - 0s 15ms/step
[[18.476917 19.16981 ]]
1/1 [==============================] - 0s 14ms/step
[[18.698996 18.721268]]
1/1 [==============================] - 0s 14ms/step
[[18.789513 18.087399]]
1/1 [==============================] - 0s 13ms/step
[[18.487064 18.455408]]
1/1 [==============================] - 0s 14ms/step
[[18.324936 19.011887]]
1/1 [==============================] - 0s 13ms/step
[[18.558886 18.568087]]
1/1 [==============================] - 0s 14ms/step
[[18.661133 17.937439]]
1/1 [==============================] - 0s 14ms/step
[[18.367   18.30494]]
1/1 [==============================] - 0s 13ms/step
[[18.21697  18.861118]]
1/1 [==============================] - 0s 14ms/step
[[18.467606 18.420576]]
1/1 [==============================] - 0s 14ms/step
[[18.299995 18.970432]]
1/1 [==============================] - 0s 14ms/step
[[18.540695 18.530844]]
1/1 [=========

1/1 [==============================] - 0s 14ms/step
[[18.512833 18.548365]]
1/1 [==============================] - 0s 16ms/step
[[18.62157  17.922539]]
1/1 [==============================] - 0s 15ms/step
[[18.3275   18.294647]]
1/1 [==============================] - 0s 13ms/step
[[18.169897 18.85311 ]]
1/1 [==============================] - 0s 16ms/step
[[18.428522 18.417751]]
1/1 [==============================] - 0s 16ms/step
[[18.262505 18.971745]]
1/1 [==============================] - 0s 17ms/step
[[18.509686 18.528646]]
1/1 [==============================] - 0s 14ms/step
[[18.62189  17.898298]]
1/1 [==============================] - 0s 15ms/step
[[34.686554 32.104225]]
1/1 [==============================] - 0s 14ms/step
[[34.527206 32.819683]]
1/1 [==============================] - 0s 14ms/step
[[34.48276  33.719112]]
1/1 [==============================] - 0s 14ms/step
[[34.533623 34.794033]]
1/1 [==============================] - 0s 15ms/step
[[35.066727 34.637173]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[31.380459 32.036697]]
1/1 [==============================] - 0s 15ms/step
[[30.862612 31.037827]]
1/1 [==============================] - 0s 16ms/step
[[30.182743 29.89963 ]]
1/1 [==============================] - 0s 15ms/step
[[29.26348 29.87256]]
1/1 [==============================] - 0s 14ms/step
[[28.630571 28.769854]]
1/1 [==============================] - 0s 15ms/step
[[27.888847 27.497873]]
1/1 [==============================] - 0s 15ms/step
[[26.88096  27.333307]]
1/1 [==============================] - 0s 15ms/step
[[26.16488  26.089119]]
1/1 [==============================] - 0s 15ms/step
[[25.235142 25.967182]]
1/1 [==============================] - 0s 19ms/step
[[24.59315 24.76449]]
1/1 [==============================] - 0s 15ms/step
[[23.80859  23.377956]]
1/1 [==============================] - 0s 15ms/step
[[22.82955  23.124998]]
1/1 [==============================] - 0s 14ms/step
[[22.144564 21.781826]]
1/1 [===========

1/1 [==============================] - 0s 14ms/step
[[15.6398    14.8380785]]
1/1 [==============================] - 0s 13ms/step
[[15.600287 15.248869]]
1/1 [==============================] - 0s 14ms/step
[[15.702885 15.836869]]
1/1 [==============================] - 0s 14ms/step
[[15.906715 15.237149]]
1/1 [==============================] - 0s 14ms/step
[[16.002728 15.798946]]
1/1 [==============================] - 0s 13ms/step
[[16.234604 16.536541]]
1/1 [==============================] - 0s 13ms/step
[[16.563612 16.087156]]
1/1 [==============================] - 0s 14ms/step
[[16.766027 16.792803]]
1/1 [==============================] - 0s 13ms/step
[[17.080666 16.317533]]
1/1 [==============================] - 0s 13ms/step
[[17.265566 16.995275]]
1/1 [==============================] - 0s 14ms/step
[[17.578783 17.847467]]
1/1 [==============================] - 0s 14ms/step
[[17.99165 17.51432]]
1/1 [==============================] - 0s 14ms/step
[[18.257204 18.326866]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[21.378675 20.874588]]
1/1 [==============================] - 0s 13ms/step
[[21.351967 21.525583]]
1/1 [==============================] - 0s 14ms/step
[[21.440826 21.00049 ]]
1/1 [==============================] - 0s 14ms/step
[[21.404774 21.650215]]
1/1 [==============================] - 0s 14ms/step
[[21.416872 20.4093  ]]
1/1 [==============================] - 0s 14ms/step
[[21.243475 20.87802 ]]
1/1 [==============================] - 0s 13ms/step
[[21.204714 21.533127]]
1/1 [==============================] - 0s 15ms/step
[[21.27781  21.011251]]
1/1 [==============================] - 0s 13ms/step
[[21.219303 21.660055]]
1/1 [==============================] - 0s 14ms/step
[[21.272131 21.135271]]
1/1 [==============================] - 0s 13ms/step
[[21.19684  21.783533]]
1/1 [==============================] - 0s 14ms/step
[[21.240925 21.25958 ]]
1/1 [==============================] - 0s 13ms/step
[[21.14268  20.551289]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[18.535343 18.540064]]
1/1 [==============================] - 0s 14ms/step
[[18.355621 17.704481]]
1/1 [==============================] - 0s 14ms/step
[[18.056557 18.042015]]
1/1 [==============================] - 0s 14ms/step
[[17.908928 18.572624]]
1/1 [==============================] - 0s 14ms/step
[[17.89997 17.93491]]
1/1 [==============================] - 0s 14ms/step
[[17.762402 17.11197 ]]
1/1 [==============================] - 0s 14ms/step
[[17.514618 17.466492]]
1/1 [==============================] - 0s 14ms/step
[[17.379667 18.000578]]
1/1 [==============================] - 0s 14ms/step
[[17.37646  17.359959]]
1/1 [==============================] - 0s 14ms/step
[[17.267054 17.900925]]
1/1 [==============================] - 0s 12ms/step
[[17.29576  17.268896]]
1/1 [==============================] - 0s 13ms/step
[[17.212097 17.815996]]
1/1 [==============================] - 0s 15ms/step
[[17.272112 17.193186]]
1/1 [=========

1/1 [==============================] - 0s 14ms/step
[[18.2284   18.060461]]
1/1 [==============================] - 0s 13ms/step
[[18.24736  18.718508]]
1/1 [==============================] - 0s 14ms/step
[[18.384296 18.206577]]
1/1 [==============================] - 0s 15ms/step
[[18.398396 18.857351]]
1/1 [==============================] - 0s 14ms/step
[[18.531033 18.342287]]
1/1 [==============================] - 0s 13ms/step
[[18.545704 18.99237 ]]
1/1 [==============================] - 0s 13ms/step
[[18.682102 18.47845 ]]
1/1 [==============================] - 0s 14ms/step
[[18.691303 19.123419]]
1/1 [==============================] - 0s 14ms/step
[[18.815722 18.607119]]
1/1 [==============================] - 0s 15ms/step
[[18.8108   19.246546]]
1/1 [==============================] - 0s 15ms/step
[[18.912498 18.723356]]
1/1 [==============================] - 0s 14ms/step
[[18.88637  19.352804]]
1/1 [==============================] - 0s 14ms/step
[[18.980635 18.828152]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[17.829645 17.180593]]
1/1 [==============================] - 0s 13ms/step
[[17.709883 17.657803]]
1/1 [==============================] - 0s 13ms/step
[[17.725792 18.316833]]
1/1 [==============================] - 0s 14ms/step
[[17.91281  17.854307]]
1/1 [==============================] - 0s 14ms/step
[[17.921375 18.506794]]
1/1 [==============================] - 0s 13ms/step
[[18.099277 18.03713 ]]
1/1 [==============================] - 0s 13ms/step
[[18.057674 18.66657 ]]
1/1 [==============================] - 0s 14ms/step
[[18.184717 18.174553]]
1/1 [==============================] - 0s 14ms/step
[[18.134066 18.79599 ]]
1/1 [==============================] - 0s 13ms/step
[[18.255154 18.298353]]
1/1 [==============================] - 0s 15ms/step
[[18.243647 17.617622]]
1/1 [==============================] - 0s 14ms/step
[[18.072289 18.059885]]
1/1 [==============================] - 0s 14ms/step
[[18.050726 18.692692]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[18.072256 18.075739]]
1/1 [==============================] - 0s 15ms/step
[[18.087885 17.42071 ]]
1/1 [==============================] - 0s 13ms/step
[[17.92012  17.867796]]
1/1 [==============================] - 0s 14ms/step
[[17.881119 18.49491 ]]
1/1 [==============================] - 0s 14ms/step
[[18.031559 18.02076 ]]
1/1 [==============================] - 0s 14ms/step
[[17.986193 18.642292]]
1/1 [==============================] - 0s 14ms/step
[[18.130867 18.16377 ]]
1/1 [==============================] - 0s 14ms/step
[[18.146683 17.502579]]
1/1 [==============================] - 0s 15ms/step
[[17.934618 17.929564]]
1/1 [==============================] - 0s 14ms/step
[[17.871386 18.545113]]
1/1 [==============================] - 0s 13ms/step
[[18.003647 18.064392]]
1/1 [==============================] - 0s 14ms/step
[[18.01062  17.401476]]
1/1 [==============================] - 0s 14ms/step
[[17.838526 17.843866]]
1/1 [=======

1/1 [==============================] - 0s 15ms/step
[[18.716043 19.344519]]
1/1 [==============================] - 0s 14ms/step
[[18.824837 18.835386]]
1/1 [==============================] - 0s 14ms/step
[[18.793684 18.141897]]
1/1 [==============================] - 0s 14ms/step
[[18.61559  18.565619]]
1/1 [==============================] - 0s 13ms/step
[[18.5771   19.176094]]
1/1 [==============================] - 0s 15ms/step
[[18.684092 18.671364]]
1/1 [==============================] - 0s 14ms/step
[[18.631285 19.27481 ]]
1/1 [==============================] - 0s 13ms/step
[[18.735703 18.773396]]
1/1 [==============================] - 0s 14ms/step
[[18.700115 18.087324]]
1/1 [==============================] - 0s 15ms/step
[[18.513096 18.50743 ]]
1/1 [==============================] - 0s 13ms/step
[[18.456182 19.108484]]
1/1 [==============================] - 0s 14ms/step
[[18.563116 18.610254]]
1/1 [==============================] - 0s 14ms/step
[[18.535212 17.930637]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[18.014904 17.966166]]
1/1 [==============================] - 0s 13ms/step
[[18.004343 18.595089]]
1/1 [==============================] - 0s 14ms/step
[[18.17274  18.134346]]
1/1 [==============================] - 0s 15ms/step
[[18.14279 18.74936]]
1/1 [==============================] - 0s 15ms/step
[[18.29707  18.279013]]
1/1 [==============================] - 0s 14ms/step
[[18.25347  18.887001]]
1/1 [==============================] - 0s 14ms/step
[[18.396595 18.41484 ]]
1/1 [==============================] - 0s 13ms/step
[[18.412096 17.762186]]
1/1 [==============================] - 0s 14ms/step
[[18.236664 18.188875]]
1/1 [==============================] - 0s 14ms/step
[[18.202925 18.799725]]
1/1 [==============================] - 0s 14ms/step
[[18.364506 18.332172]]
1/1 [==============================] - 0s 14ms/step
[[18.313265 18.932701]]
1/1 [==============================] - 0s 13ms/step
[[18.464956 18.459694]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.645    18.161049]]
1/1 [==============================] - 0s 14ms/step
[[18.412903 18.561493]]
1/1 [==============================] - 0s 14ms/step
[[18.426006 17.920399]]
1/1 [==============================] - 0s 13ms/step
[[18.208864 18.329529]]
1/1 [==============================] - 0s 14ms/step
[[18.230665 17.69479 ]]
1/1 [==============================] - 0s 13ms/step
[[18.017185 18.107174]]
1/1 [==============================] - 0s 14ms/step
[[18.050192 17.478786]]
1/1 [==============================] - 0s 14ms/step
[[17.901379 17.279718]]
1/1 [==============================] - 0s 14ms/step
[[17.724884 17.710566]]
1/1 [==============================] - 0s 13ms/step
[[17.685062 18.325012]]
1/1 [==============================] - 0s 14ms/step
[[17.877504 17.888521]]
1/1 [==============================] - 0s 14ms/step
[[17.933783 17.267027]]
1/1 [==============================] - 0s 14ms/step
[[17.714579 17.681305]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[18.709173 18.617699]]
1/1 [==============================] - 0s 13ms/step
[[18.631983 19.192253]]
1/1 [==============================] - 0s 14ms/step
[[18.764584 18.702316]]
1/1 [==============================] - 0s 13ms/step
[[18.659666 19.267168]]
1/1 [==============================] - 0s 14ms/step
[[18.776745 18.777153]]
1/1 [==============================] - 0s 14ms/step
[[18.76281  18.109089]]
1/1 [==============================] - 0s 13ms/step
[[18.529562 18.49933 ]]
1/1 [==============================] - 0s 13ms/step
[[18.427864 19.07416 ]]
1/1 [==============================] - 0s 13ms/step
[[18.560932 18.602352]]
1/1 [==============================] - 0s 13ms/step
[[18.525064 17.938131]]
1/1 [==============================] - 0s 13ms/step
[[18.27196 18.32981]]
1/1 [==============================] - 0s 13ms/step
[[18.273514 17.681206]]
1/1 [==============================] - 0s 13ms/step
[[18.059677 18.091179]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.40642 18.97891]]
1/1 [==============================] - 0s 15ms/step
[[18.582829 18.52436 ]]
1/1 [==============================] - 0s 15ms/step
[[18.518444 19.107904]]
1/1 [==============================] - 0s 13ms/step
[[18.674107 18.64324 ]]
1/1 [==============================] - 0s 14ms/step
[[18.585714 19.214739]]
1/1 [==============================] - 0s 13ms/step
[[18.721222 18.741602]]
1/1 [==============================] - 0s 14ms/step
[[18.726845 18.088604]]
1/1 [==============================] - 0s 13ms/step
[[18.503527 18.476027]]
1/1 [==============================] - 0s 14ms/step
[[18.416426 19.045176]]
1/1 [==============================] - 0s 13ms/step
[[18.553865 18.575071]]
1/1 [==============================] - 0s 14ms/step
[[18.559443 17.925468]]
1/1 [==============================] - 0s 13ms/step
[[18.330069 18.308922]]
1/1 [==============================] - 0s 14ms/step
[[18.239668 18.876953]]
1/1 [=========

1/1 [==============================] - 0s 13ms/step
[[18.998186 18.688002]]
1/1 [==============================] - 0s 13ms/step
[[18.908615 19.244352]]
1/1 [==============================] - 0s 13ms/step
[[19.096674 18.804798]]
1/1 [==============================] - 0s 13ms/step
[[18.991598 19.35229 ]]
1/1 [==============================] - 0s 14ms/step
[[19.161966 18.905344]]
1/1 [==============================] - 0s 13ms/step
[[19.033426 19.444317]]
1/1 [==============================] - 0s 13ms/step
[[19.197443 18.997017]]
1/1 [==============================] - 0s 13ms/step
[[19.060314 19.531748]]
1/1 [==============================] - 0s 13ms/step
[[19.214996 19.077713]]
1/1 [==============================] - 0s 13ms/step
[[19.068533 19.605988]]
1/1 [==============================] - 0s 13ms/step
[[19.214636 19.149303]]
1/1 [==============================] - 0s 14ms/step
[[19.054796 19.671455]]
1/1 [==============================] - 0s 14ms/step
[[19.015566 19.729013]]
1/1 [=======

1/1 [==============================] - 0s 13ms/step
[[18.432049 18.442144]]
1/1 [==============================] - 0s 13ms/step
[[18.496918 17.846037]]
1/1 [==============================] - 0s 13ms/step
[[18.255795 18.223766]]
1/1 [==============================] - 0s 13ms/step
[[18.13762  18.778112]]
1/1 [==============================] - 0s 14ms/step
[[18.33172  18.360907]]
1/1 [==============================] - 0s 14ms/step
[[18.395313 17.763117]]
1/1 [==============================] - 0s 14ms/step
[[18.231611 17.544018]]
1/1 [==============================] - 0s 14ms/step
[[17.962276 17.908665]]
1/1 [==============================] - 0s 19ms/step
[[17.834778 18.462286]]
1/1 [==============================] - 0s 14ms/step
[[18.030224 18.048594]]
1/1 [==============================] - 0s 14ms/step
[[18.099167 17.455986]]
1/1 [==============================] - 0s 13ms/step
[[17.874521 17.843256]]
1/1 [==============================] - 0s 14ms/step
[[17.799374 18.416325]]
1/1 [=======

1/1 [==============================] - 0s 14ms/step
[[18.347822 17.752928]]
1/1 [==============================] - 0s 13ms/step
[[18.136953 18.134516]]
1/1 [==============================] - 0s 13ms/step
[[18.067911 18.699196]]
1/1 [==============================] - 0s 13ms/step
[[18.293028 18.29173 ]]
1/1 [==============================] - 0s 15ms/step
[[18.231216 18.855637]]
1/1 [==============================] - 0s 12ms/step
[[18.456324 18.444239]]
1/1 [==============================] - 0s 13ms/step
[[18.389029 19.004671]]
1/1 [==============================] - 0s 14ms/step
[[18.610811 18.592192]]
1/1 [==============================] - 0s 14ms/step
[[18.53441 19.14572]]
1/1 [==============================] - 0s 15ms/step
[[18.74744  18.730957]]
1/1 [==============================] - 0s 13ms/step
[[18.658173 19.276997]]
1/1 [==============================] - 0s 14ms/step
[[18.858097 18.857176]]
1/1 [==============================] - 0s 13ms/step
[[18.756254 19.39686 ]]
1/1 [=========

1/1 [==============================] - 0s 14ms/step
[[18.724487 18.699936]]
1/1 [==============================] - 0s 13ms/step
[[18.622072 19.234377]]
1/1 [==============================] - 0s 14ms/step
[[18.813854 18.817915]]
1/1 [==============================] - 0s 14ms/step
[[18.876705 18.226025]]
1/1 [==============================] - 0s 13ms/step
[[18.527323 19.10793 ]]
1/1 [==============================] - 0s 13ms/step
[[18.72889 18.70098]]
1/1 [==============================] - 0s 14ms/step
[[18.601238 19.222334]]
1/1 [==============================] - 0s 14ms/step
[[18.78632  18.811188]]
1/1 [==============================] - 0s 14ms/step
[[18.838385 18.22038 ]]
1/1 [==============================] - 0s 13ms/step
[[18.575674 18.561705]]
1/1 [==============================] - 0s 13ms/step
[[18.411703 19.074043]]
1/1 [==============================] - 0s 4ms/step - loss: 0.0418 - accuracy: 0.8438


In [199]:
def get_best_action(obs):
    q_vals = updated_model.predict(obs, verbose = 0)
    return np.argmax(q_vals)

In [207]:
#Run the currant model with best actions
obs, info = env.reset(return_info=True)
done = False
score = 0
while not done:
    obs, reward, done, info = env.step(get_best_action(np.array(obs).reshape(-1, 4)))
    score += reward
    env.render()
print(score)

500.0


In [170]:
len(replay_memory)

4837

In [173]:
epsilon

0.025817827831345935